name: Test

on:
  push:
    branches:
      - "**"

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
      - uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: "30.x"
      - run: make proto
      - name: Build binary
        run: CGO_ENABLED=0 go build -trimpath -ldflags="-w -s -extldflags '-static'"
      - name: Run test
        run: |
          ./example-extension -f config.yaml &
          sleep 2
          curl --max-time 10 "http://localhost:8080/get"
