// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.0
// source: ext/v1/hello.proto

package v1

import (
	kernel "github.com/aileron-gateway/aileron-gateway/apis/kernel"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HelloHeaderMiddleware is the top level definition
// for configurations of the middleware.
// The structure must be same for all resources.
type HelloHeaderMiddleware struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// APIVersion is api version of the middleware.
	// The api version is defined in the Go code.
	// "ext/v1" should be specified in this example project.
	APIVersion string `protobuf:"bytes,1,opt,name=APIVersion,json=apiVersion,proto3" json:"APIVersion,omitempty"`
	// Kind is the resource name of the middleware.
	// The name  is defined in the Go code.
	// "HelloHeaderMiddleware" should be specified in this example project.
	Kind string `protobuf:"bytes,2,opt,name=Kind,json=kind,proto3" json:"Kind,omitempty"`
	// Metadata is the metadata of the middleware.
	// It contains "name" and "namespace".
	// They can be used to make multiple instance of the middleware.
	// If not specified in configuration, both "name" and "namespace"
	// will becomes "default".
	Metadata *kernel.Metadata `protobuf:"bytes,3,opt,name=Metadata,json=metadata,proto3" json:"Metadata,omitempty"`
	// Status is the status of the middleware.
	// This item must be managed in the codes and should not
	// be set in configuration files.
	Status *kernel.Status `protobuf:"bytes,4,opt,name=Status,json=status,proto3" json:"Status,omitempty"`
	// Spec is the main specifications for the middleware.
	// All middleware specific configurations should go in the spec.
	Spec          *HelloHeaderMiddlewareSpec `protobuf:"bytes,5,opt,name=Spec,json=spec,proto3" json:"Spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloHeaderMiddleware) Reset() {
	*x = HelloHeaderMiddleware{}
	mi := &file_ext_v1_hello_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloHeaderMiddleware) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloHeaderMiddleware) ProtoMessage() {}

func (x *HelloHeaderMiddleware) ProtoReflect() protoreflect.Message {
	mi := &file_ext_v1_hello_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloHeaderMiddleware.ProtoReflect.Descriptor instead.
func (*HelloHeaderMiddleware) Descriptor() ([]byte, []int) {
	return file_ext_v1_hello_proto_rawDescGZIP(), []int{0}
}

func (x *HelloHeaderMiddleware) GetAPIVersion() string {
	if x != nil {
		return x.APIVersion
	}
	return ""
}

func (x *HelloHeaderMiddleware) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *HelloHeaderMiddleware) GetMetadata() *kernel.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *HelloHeaderMiddleware) GetStatus() *kernel.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *HelloHeaderMiddleware) GetSpec() *HelloHeaderMiddlewareSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

// HelloHeaderMiddlewareSpec is the middleware specific configurations.
type HelloHeaderMiddlewareSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ErrorHandler is the reference to a error handler resource.
	// It is used to return HTTP errors to clients when
	// some error occurred.
	ErrorHandler *kernel.Reference `protobuf:"bytes,1,opt,name=ErrorHandler,json=errorHandler,proto3" json:"ErrorHandler,omitempty"`
	// Value is the "Hello" header value.
	Value         string `protobuf:"bytes,2,opt,name=Value,json=value,proto3" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloHeaderMiddlewareSpec) Reset() {
	*x = HelloHeaderMiddlewareSpec{}
	mi := &file_ext_v1_hello_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloHeaderMiddlewareSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloHeaderMiddlewareSpec) ProtoMessage() {}

func (x *HelloHeaderMiddlewareSpec) ProtoReflect() protoreflect.Message {
	mi := &file_ext_v1_hello_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloHeaderMiddlewareSpec.ProtoReflect.Descriptor instead.
func (*HelloHeaderMiddlewareSpec) Descriptor() ([]byte, []int) {
	return file_ext_v1_hello_proto_rawDescGZIP(), []int{1}
}

func (x *HelloHeaderMiddlewareSpec) GetErrorHandler() *kernel.Reference {
	if x != nil {
		return x.ErrorHandler
	}
	return nil
}

func (x *HelloHeaderMiddlewareSpec) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_ext_v1_hello_proto protoreflect.FileDescriptor

const file_ext_v1_hello_proto_rawDesc = "" +
	"\n" +
	"\x12ext/v1/hello.proto\x12\x06ext.v1\x1a\x15kernel/resource.proto\"\xd8\x01\n" +
	"\x15HelloHeaderMiddleware\x12\x1e\n" +
	"\n" +
	"APIVersion\x18\x01 \x01(\tR\n" +
	"apiVersion\x12\x12\n" +
	"\x04Kind\x18\x02 \x01(\tR\x04kind\x12,\n" +
	"\bMetadata\x18\x03 \x01(\v2\x10.kernel.MetadataR\bmetadata\x12&\n" +
	"\x06Status\x18\x04 \x01(\v2\x0e.kernel.StatusR\x06status\x125\n" +
	"\x04Spec\x18\x05 \x01(\v2!.ext.v1.HelloHeaderMiddlewareSpecR\x04spec\"h\n" +
	"\x19HelloHeaderMiddlewareSpec\x125\n" +
	"\fErrorHandler\x18\x01 \x01(\v2\x11.kernel.ReferenceR\ferrorHandler\x12\x14\n" +
	"\x05Value\x18\x02 \x01(\tR\x05valueB:Z8github.com/aileron-gateway/example-extension/apis/ext/v1b\x06proto3"

var (
	file_ext_v1_hello_proto_rawDescOnce sync.Once
	file_ext_v1_hello_proto_rawDescData []byte
)

func file_ext_v1_hello_proto_rawDescGZIP() []byte {
	file_ext_v1_hello_proto_rawDescOnce.Do(func() {
		file_ext_v1_hello_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ext_v1_hello_proto_rawDesc), len(file_ext_v1_hello_proto_rawDesc)))
	})
	return file_ext_v1_hello_proto_rawDescData
}

var file_ext_v1_hello_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ext_v1_hello_proto_goTypes = []any{
	(*HelloHeaderMiddleware)(nil),     // 0: ext.v1.HelloHeaderMiddleware
	(*HelloHeaderMiddlewareSpec)(nil), // 1: ext.v1.HelloHeaderMiddlewareSpec
	(*kernel.Metadata)(nil),           // 2: kernel.Metadata
	(*kernel.Status)(nil),             // 3: kernel.Status
	(*kernel.Reference)(nil),          // 4: kernel.Reference
}
var file_ext_v1_hello_proto_depIdxs = []int32{
	2, // 0: ext.v1.HelloHeaderMiddleware.Metadata:type_name -> kernel.Metadata
	3, // 1: ext.v1.HelloHeaderMiddleware.Status:type_name -> kernel.Status
	1, // 2: ext.v1.HelloHeaderMiddleware.Spec:type_name -> ext.v1.HelloHeaderMiddlewareSpec
	4, // 3: ext.v1.HelloHeaderMiddlewareSpec.ErrorHandler:type_name -> kernel.Reference
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_ext_v1_hello_proto_init() }
func file_ext_v1_hello_proto_init() {
	if File_ext_v1_hello_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ext_v1_hello_proto_rawDesc), len(file_ext_v1_hello_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ext_v1_hello_proto_goTypes,
		DependencyIndexes: file_ext_v1_hello_proto_depIdxs,
		MessageInfos:      file_ext_v1_hello_proto_msgTypes,
	}.Build()
	File_ext_v1_hello_proto = out.File
	file_ext_v1_hello_proto_goTypes = nil
	file_ext_v1_hello_proto_depIdxs = nil
}
